---
# Run when  OS is Ubuntu
- name: Found Ubuntu version
  debug:
    msg: "Ubuntu version {{ ansible_facts['distribution_major_version'] }}"

- name: Upgrade all existed apt packages
  apt: upgrade=dist force_apt_get=yes

- name: Enable sudo and build-essential for installation
  apt: name="sudo,curl,build-essential,pkg-config,libssl-dev" state=present
  tags:
    - common
    - packages
    - sudo

- name: Extension debian packages 
  debug: var=extension_ubuntu_packages

- name: Install rustup
  shell: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y

- name: Install extension packages
  shell: |
    . $HOME/.cargo/env
    if ! type "{{item}}" > /dev/null; then
      cargo install {{item}}
    fi
  with_items: "{{extension_ubuntu_packages}}"

#- name: Install common extension packages
#  apt: name={{ extension_ubuntu_packages }} state=present
#  ignore_errors: true
#  tags:
#    - common
#    - extension
#    - packages
#    - general
